### PR TITLE
Routine updates to allow for JDK11 compatibility

### PR DESCRIPTION
**Pull request by Vlatombe**
* Update parent POM
* Bump Jenkins to 2.289.3
* Remove plugin specifics enforcer that don't make sense nowadays.
* Remove unused dependencies.
* Use BOM.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by alecharp — APPROVED** [review]

**Comment by mikecirioli** [comment]
ping @rsandell  for review/merge please

**Comment by jtnord** [comment]
is the plugin really not compatable with java11 - there is so little code here I would be amazed if it did not work.

**Comment by mikecirioli** [comment]
@stephenc do you have merge rights on this repo?

**Comment by batmat** [comment]
I will merge this after I've landed https://github.com/jenkinsci/deployed-on-column-plugin/pull/5

**Comment by batmat** [comment]
Included in https://github.com/jenkinsci/deployed-on-column-plugin/pull/5

**Pull request closed without merging**
