### PR TITLE
Disable showing the column by default.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by aheritier** [comment]
why?

**Comment by christ66** [comment]
@aheritier Setting the "show by default" option changes the default view for every folder created. If I create 20 new folders each will have the deploy on column even if the folder doesn't use it. It just adds more to the default view as well which can not be modified, so you're All view will have this column until a new view is created.

I think it would be better to disable it by default and you select which views and which folders get the view.

**Review by jglick — APPROVED** [review]
:bee:

**Comment by aheritier** [comment]
🐝

**Pull request merged**
